#! /usr/bin/env ruby

require 'optparse'

options = {}

opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage: #{$PROGRAM_NAME} [OPTIONS]"
  opt.separator ''
  opt.separator 'OPTIONS'

  opt.on('-h', '--heading HEADING', 'a heading to display.') do |heading|
    options[:heading] = heading
  end
  opt.on('-v', '--verbose', 'be more chatty') do
    options[:verbose] = true
  end
  opt.on('-h', '--help', 'Wypisz pomoc') do
    puts opt
    exit
  end
end
opt_parser.parse!

puts options[:heading] unless options[:heading].nil?

ARGF.each_line do |line|
  puts line
end
