AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '**/Gemfile'

Metrics/LineLength:
  Max: 80

Style/StringLiterals:
  Enabled: true

Metrics/BlockLength:
  Enabled: false
